language: ruby
rvm:
- 2.6.3

before_install: gem update bundler
install:
  - bundle install

before_script:
- chmod +x ./setup
script: "./setup"
branches:
  only:
  - gh-pages
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler
notifications:
  email: false
