safe: false
lsi: false
pygments: true

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise

branch: master

include:
  - _static

permalink: pretty

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - "*.Rmd"
  - vendor
  - .travis.yml
